name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13
      - name: Install Elixir Dependencies
        run: mix deps.get
      - name: Lint
        run: |
          mix compile --warnings-as-errors --force
          mix credo --strict
      - name: Run Tests
        run: mix test
